name: face_recognition_app
description: A Flutter app for face recognition authentication.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.11.1
  http: ^0.13.5
  sqflite: ^2.4.2
  flutter_application_1: ^0.0.2
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.4
  lottie: ^3.0.0
  fl_chart: ^0.70.2
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
