name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  sqflite: ^2.4.2  # Updated to the latest version
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  http: ^1.3.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^9.0.0
  dio: ^5.3.2
  fl_chart: ^0.70.2
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loading.json
